### ISSUE TITLE
Packages containing underscore in name

### ISSUE THREAD

**Issue by ArnoStrouwen** [julia-actions/julia-downgrade-compat#6]
There are many packages which have a `_jll` in their name:
https://github.com/JuliaBinaryWrappers

I think the regex in this CI struggels with them?

**Comment by JoshuaLampert** [comment]
This has already been fixed in https://github.com/cjdoris/julia-downgrade-compat-action/pull/2 and is available in the release [v1.0.7](https://github.com/julia-actions/julia-downgrade-compat/releases/tag/v1.0.7).

**Comment by cjdoris** [comment]
Yes indeed this is fixed now. There was an issue with tags that I just fixed so any existing workflows should work if you re-run them.
